modified

diff --git a/Anime download/anime_watcher b/Anime download/anime_watcher
--- a/Anime download/anime_watcher
+++ b/Anime download/anime_watcher
@@ -15,10 +15,8 @@ filter="${folder}/.filter"
 exitfile="${folder}/.aria2_exit" # exit file https://raw.githubusercontent.com/tomiia/bazar/master/Anime%20download/.aria2_exit
 
 exit_print() {
-    printf "\"%s\" episode %s : $(grep "^${exitcode} .*$" "${errorfile}" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')\n\n" "${name}" "${ep}"
+    printf "\"%s\" episode %s : %s\n\n" "${name}" "${ep}" "$(grep "^$1 .*$" "${errorfile}" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')"
 }
-
-clear;tmux clearhist -t downloads:2.1
 
 rsstail -PlHNr -u 'http://www.nyaa.se/?page=rss&cats=1_37&user=64513&term=720p+-batch' 2>/dev/null | \
 
@@ -27,19 +25,17 @@ while read -r anime; do
     read -r url
 
     if grep --quiet --file="${filter}" <<< ${anime}; then
-
         name="$(sed -r 's/[^ ]+ (.*) - [^-]+/\1/' <<< ${anime})"
         ep=$(sed -r 's/.* - ([^ ]+) [^-]+/\1/' <<< ${anime})
         dldir="${folder}/${name}"
         
         if [ ! -e "${dldir}" ]; then
-            mkdir -p "${dldir}" || dldir="${folder}" # if an error occurs with mkdir, fallback to ${folder} dir
+            mkdir -p "${dldir}" || printf "%s\n" "ERROR \"${dldir}\""
         fi
         
         aria2c --quiet=true --dir="${dldir}" "${url}"
-        exitcode="$?"
 
-        exit_print
+        exit_print "$?"
 
     fi
 
